# this is the name of the 'workflow'
name: 'SecondWorkflow'
#
# this is the 'event' for this workflow
# means when will it be executed
# in this case there is a dependency to the first workflow
on:
  workflow_run:
    workflows: [FirstWorkflow]
    types: [completed]
# 
# section, which contains the job-definitions
# each job contains one step at least
# but it can also contain more than one step
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Werte der Variablen:'
      - run: echo ${{ github.workflow.name}} 
#      - run: echo ${{ github.event.workflow_run.types}} 
      - run: echo ${{ github.event.workflow_run.conclusion}}
      - run: echo 'The first workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Werte der Variablen:'
      - run: echo ${{ github.workflow.name}} 
#      - run: echo ${{ github.event.workflow_run.types}} 
      - run: echo ${{ github.event.workflow_run.conclusion}}
      - run: echo 'The first workflow failed'
# 
